nome = str(input('qual e o nome da vitima todo? ')).strip()
print('-' * 20)
print('#CARREGANDO O NOME DA VITIMA.')
print(f'o nome dela com todas as letras maiusculas: {nome.upper()}')
print(f'o nome dela com todas as letras minusculas: {nome.lower()}')
print(f'o nome dela total de letras {len(nome)- nome.count(' ')}') 
print(f'Total de letras no primeiro nome da vitima: {nome.find(' ')}')
print('SISTEMA OPERADOR, CARREGADO COM SUCESSO.')
print('-' * 20)
#dividido = (frase.split())
#print(dividido[2] [3])
#frase = frase.replace('python', 'android')
#print(frase.lower().find('video'))