tot_brasileirao = ('Palmeiras', 'Flamengo', 'Fluminense', 'Athletico-PR', 'Bragantino', 'Bahia', 'Coritiba', 'São paulo', 'Athletico-MG', 'Corinthians', 'Cruzeiro', 'Botafogo', 'vitoria', 'Internacional', 'Santos', 'Gremio', 'Vasco', 'Remo', 'Mirassol', 'Chapecoense')
print('-=' * 20)
print(f'LISTA DE TIMES DO BRASILEIRAO: {tot_brasileirao}')
print('-=' * 20)
print(f'OS 5 PRIMEIROS SAO: {tot_brasileirao[0:5]}')
print('-=' * 20)
print(f'OS 4 ULTIMOS SAO: {tot_brasileirao[16:]}')
print('-=' * 20)
print(f'TIME EM ORDEM ALFABETICA: {sorted(tot_brasileirao)}')
print('-=' * 20)
print(f'Chapacoense esta na posiçao {tot_brasileirao.index('Chapecoense') + 1}')